### PR TITLE
#270 Back port fix from cep-18 + #267 nft_kind should be optional on install + default

### LINKED ISSUE #267: CEP78 / nft_kind should be optional on install + default

### LINKED ISSUE #270: CEP78 / Back port fix from cep-18
https://github.com/casper-ecosystem/cep18/pull/133

### PR DESCRIPTION
**Pull request by gRoussac**
#270 Back port fix from cep-18
#267 nft_kind should be optional on install + default

### CODE REVIEW

**Review by ACStone-MTS — APPROVED** [review]
Changes to Markdown files look good to me!

**Review by deuszex — APPROVED** [review]
code part looks good

**Comment by gRoussac** [comment]
@deuszex now It misses the fix we need to opt for 

```
Err(_) => runtime::revert(invalid),
```
let me know what you decide in cep-18

**Comment by gRoussac** [comment]
I have set 

```
Err(e) => runtime::revert(e),
```

**Pull request merged**
