### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hoffmannjan**
Fixed typos and added URL to npmjs.

Before merging - please merge [this first](https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/116) as there might be some possible conflicts.

### CODE REVIEW

**Review by ACStone-MTS — APPROVED** [review]

**Review by ipopescu — APPROVED** [review]
LGTM! But, the build is breaking, and I wasn't able to fix it. I wonder if the build machine needs an npm update or an "npm audit fix --force". Locally, everything is fine.
I added a few minor edits as I was reading through the file.

**Comment by hoffmannjan** [comment]
@ipopescu ok I'll look into it :)

**Comment by hoffmannjan** [comment]
it's fixed in this PR :) https://github.com/casper-ecosystem/cep-78-enhanced-nft/pull/120

**Comment by ipopescu** [comment]
Great, thanks @hoffmannjan!

**Pull request merged**
